version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run:
          name: Building
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then 
                  npm run build-prod

              else
                  echo "ERROR: not build branch ${CIRCLE_BRANCH}"
                  exit 1
              fi

  deploy:
    docker:
      - image: circleci/node:9.4
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools

      - run:
          name: Deploy to Firebase
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  npm run build-prod
                  cd functions && npm install 
                  ./node_modules/.bin/firebase deploy --token=${FIREBASE_TOKEN} --non-interactive
              else
                  echo "ERROR: not deploy branch ${CIRCLE_BRANCH}"
                  exit 1
              fi
            
          
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master